baseURL = "https://d2cybersec.gitlab.io"
title = "Data Driven CyberSecurity Lab"
languageCode = "ru-RU"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Data Driven CyberSecurity Lab" # title for frontpage, may include image
copyright = "i2z1@yandex.ru"
description = '<b>Лаборатория доказательной кибербезопасности<br></b>  <br> Клуб увлеченных исследователей и инженеров'
startbuttonText = "Я в деле!"
startbuttonLink = "#three"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Сообщество Data Science исследователей в сфере информационной безопасности'
body = '''
Вне всякой зависимости от уровня подготовки, делаете ли Вы первые шаги или Вы опытный исследователь,
наше сообщество поможет найти единомышленников, новые идеи и продолжить путь в интересном мире, существующем на стыке 
двух интереснейших миров: __кибербезопасности__ и __data science__!
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/system_p.jpg"
title = 'Системный подход'
body = 'Анализ всех данных, а не отдельных индикаторов'

[[params.two.section]]
img = "img/object_view.jpg"
title = 'Объективность'
body = 'Объективная наблюдаемость происходящих процессов и четкие критерии, а не мистификация и богатый опыт прошлого'

[[params.two.section]]
img = "img/hi_math.png"
title = 'Open science'
body = 'Воспроизводимость, прозрачность и интерпретирумость результата, а не подгонка и выбор "нужных" фактов.'

[[params.two.section]]
img = "img/ML.jpg"
title = 'Автоматизация и машинное обучение'
body = 'Высокий уровень автоматизации, а не ручное "накликивание" в модных интерфейсах.'

[[params.two.section]]
img = "img/instr.png"
title = 'Инженерный подход'
body = 'Технологическая зрелость, а не самописные скрипты с красивыми названиями.'

[params.three]
enable = true
title = 'Лаборатория'
body = '''
Data Driven CyberSecurity Lab
'''

[[params.three.feature]]
icon = "fa-laptop"
title = "<a href='https://d2cybersec.gitlab.io/kb/'>База знаний</a>"
body = "Знание - сила"


[[params.three.feature]]
icon = "fa-flag-o"
title = "<a href='https://i2z1.gitlab.io/#projects'>Проекты</a>"
body = ""


[[params.three.feature]]
icon = "fa-code"
title = "<a href='https://d2cybersec.gitlab.io/kb/lab.html'>Инструментарий"
body = ""

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "<a href='https://t.me/+1WIROsfHZD05YjFi'>Сообщество"
body = ""





[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "i2z1@yandex.ru"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
